name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'doc/**'
    tags:
      - "v*"

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'doc/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: bb check
  
  deploy:
    runs-on: ubuntu-latest
    needs: [ check ]
    if: startsWith(github.ref, 'refs/tags/')
    environment: deployment
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup
    - id: info
      run: bb -m tasks.info/github-actions
    - run: bb -m tasks.deploy
      env:
        VSCE_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.info.outputs.tag }}
        files: |
          *.vsix
